spring:
  application:
    name: spring-cloud-ribbon

server:
  port: 8888

say-hello:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:9092,localhost:9999,localhost:8090
    ServerListRefreshInterval: 15000
